[package]
name = "reputation-core"
version = "0.1.0"
description = "Generic Reputation Core - Tracks prediction accuracy and participation"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "reputation_core"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.0"
