[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
problem_registry = "Fo1fm7iZpnpyCo8zbnnSN2g8zb6zFAips3hxk24NZETr"
direction_market = "8yX75Q8Go26wGTmttuVQuzMvGFYa6mWPHtGXV8vHGZzt"
treasury = "BYbmC2bdPSNELqpXqCXY9iKiDMf9hUWFdcExGiHUZSRZ"
reputation = "3FHAQavHdHT1b7YPP4jSwFZi21iAXgVoDP1tfz2XRsME"

[programs.localnet]
problem_registry = "Fo1fm7iZpnpyCo8zbnnSN2g8zb6zFAips3hxk24NZETr"
direction_market = "8yX75Q8Go26wGTmttuVQuzMvGFYa6mWPHtGXV8vHGZzt"
treasury = "BYbmC2bdPSNELqpXqCXY9iKiDMf9hUWFdcExGiHUZSRZ"
reputation = "3FHAQavHdHT1b7YPP4jSwFZi21iAXgVoDP1tfz2XRsME"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
