import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import { expect } from "chai";

// Import program types (generated by Anchor)
// These will be available after running `anchor build`

describe("Komon Programs", () => {
  // Configure the client to use the local cluster
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Keypairs for testing
  const authority = Keypair.generate();
  const creator = Keypair.generate();
  const proposer = Keypair.generate();
  const staker = Keypair.generate();

  // Program IDs (from Anchor.toml)
  const problemRegistryProgramId = new PublicKey(
    "Fo1fm7iZpnpyCo8zbnnSN2g8zb6zFAips3hxk24NZETr"
  );
  const directionMarketProgramId = new PublicKey(
    "8yX75Q8Go26wGTmttuVQuzMvGFYa6mWPHtGXV8vHGZzt"
  );
  const treasuryProgramId = new PublicKey(
    "BYbmC2bdPSNELqpXqCXY9iKiDMf9hUWFdcExGiHUZSRZ"
  );
  const reputationProgramId = new PublicKey(
    "3FHAQavHdHT1b7YPP4jSwFZi21iAXgVoDP1tfz2XRsME"
  );

  let usdcMint: PublicKey;
  let problemConfigPda: PublicKey;
  let problemPda: PublicKey;
  let marketConfigPda: PublicKey;
  let directionPda: PublicKey;
  let treasuryPda: PublicKey;
  let reputationConfigPda: PublicKey;

  before(async () => {
    // Airdrop SOL to test accounts
    const airdropPromises = [authority, creator, proposer, staker].map(
      async (keypair) => {
        const sig = await provider.connection.requestAirdrop(
          keypair.publicKey,
          2 * anchor.web3.LAMPORTS_PER_SOL
        );
        await provider.connection.confirmTransaction(sig);
      }
    );
    await Promise.all(airdropPromises);

    // Create USDC mint for testing
    usdcMint = await createMint(
      provider.connection,
      authority,
      authority.publicKey,
      null,
      6 // USDC has 6 decimals
    );

    // Derive PDAs
    [problemConfigPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("config")],
      problemRegistryProgramId
    );

    [marketConfigPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("market_config")],
      directionMarketProgramId
    );

    [treasuryPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("treasury")],
      treasuryProgramId
    );

    [reputationConfigPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("reputation_config")],
      reputationProgramId
    );
  });

  describe("Problem Registry", () => {
    it("Should initialize the problem registry config", async () => {
      // Note: This test requires the program to be deployed
      // In a real test environment, you would load the program IDL
      // and create a Program instance

      console.log("Problem Registry Config PDA:", problemConfigPda.toBase58());
      console.log("Authority:", authority.publicKey.toBase58());

      // Test initialization would go here
      // const program = anchor.workspace.ProblemRegistry as Program<ProblemRegistry>;
      // await program.methods.initialize(250).accounts({...}).rpc();
    });

    it("Should create a new problem", async () => {
      // Derive problem PDA
      const problemId = 0;
      [problemPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("problem"),
          creator.publicKey.toBuffer(),
          new anchor.BN(problemId).toArrayLike(Buffer, "le", 8),
        ],
        problemRegistryProgramId
      );

      console.log("Problem PDA:", problemPda.toBase58());

      // Test problem creation would go here
      // await program.methods.createProblem(...).accounts({...}).rpc();
    });

    it("Should fund a problem with bounty", async () => {
      // Test funding would go here
      console.log("Testing problem funding...");
    });

    it("Should update problem status", async () => {
      // Test status update would go here
      console.log("Testing status update...");
    });
  });

  describe("Direction Market", () => {
    it("Should initialize the direction market config", async () => {
      console.log("Market Config PDA:", marketConfigPda.toBase58());
      // Test initialization would go here
    });

    it("Should propose a new direction", async () => {
      // Derive direction PDA
      const directionId = 0;
      [directionPda] = PublicKey.findProgramAddressSync(
        [
          Buffer.from("direction"),
          problemPda.toBuffer(),
          new anchor.BN(directionId).toArrayLike(Buffer, "le", 8),
        ],
        directionMarketProgramId
      );

      console.log("Direction PDA:", directionPda.toBase58());
      // Test direction proposal would go here
    });

    it("Should stake on a direction (YES outcome)", async () => {
      // Test staking YES would go here
      console.log("Testing YES stake...");
    });

    it("Should stake on a direction (NO outcome)", async () => {
      // Test staking NO would go here
      console.log("Testing NO stake...");
    });

    it("Should unstake from a direction", async () => {
      // Test unstaking would go here
      console.log("Testing unstake...");
    });

    it("Should settle a direction after problem resolution", async () => {
      // Test settlement would go here
      console.log("Testing settlement...");
    });

    it("Should allow winners to claim rewards", async () => {
      // Test reward claiming would go here
      console.log("Testing reward claims...");
    });
  });

  describe("Treasury", () => {
    it("Should initialize the treasury", async () => {
      console.log("Treasury PDA:", treasuryPda.toBase58());
      // Test initialization would go here
    });

    it("Should accept deposits", async () => {
      // Test deposits would go here
      console.log("Testing deposits...");
    });

    it("Should allocate funds to problems", async () => {
      // Test allocation would go here
      console.log("Testing fund allocation...");
    });

    it("Should process payouts with fee deduction", async () => {
      // Test payouts would go here
      console.log("Testing payouts...");
    });

    it("Should allow fee withdrawal by authority", async () => {
      // Test fee withdrawal would go here
      console.log("Testing fee withdrawal...");
    });
  });

  describe("Reputation", () => {
    it("Should initialize the reputation system", async () => {
      console.log("Reputation Config PDA:", reputationConfigPda.toBase58());
      // Test initialization would go here
    });

    it("Should initialize user reputation on first action", async () => {
      // Derive reputation PDA
      const [userReputationPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("reputation"), creator.publicKey.toBuffer()],
        reputationProgramId
      );

      console.log("User Reputation PDA:", userReputationPda.toBase58());
      // Test user reputation initialization would go here
    });

    it("Should update reputation on problem posted", async () => {
      // Test problem posted tracking would go here
      console.log("Testing problem posted tracking...");
    });

    it("Should update reputation on direction proposed", async () => {
      // Test direction proposed tracking would go here
      console.log("Testing direction proposed tracking...");
    });

    it("Should update reputation on stake placed", async () => {
      // Test stake tracking would go here
      console.log("Testing stake tracking...");
    });

    it("Should update win/loss record on outcome", async () => {
      // Test outcome recording would go here
      console.log("Testing outcome recording...");
    });

    it("Should track streaks correctly", async () => {
      // Test streak tracking would go here
      console.log("Testing streak tracking...");
    });

    it("Should level up users based on XP", async () => {
      // Test level up would go here
      console.log("Testing level up...");
    });
  });

  describe("Integration Tests", () => {
    it("Should complete full problem lifecycle", async () => {
      console.log("Testing full lifecycle...");
      // 1. Create problem
      // 2. Propose directions
      // 3. Stake on directions
      // 4. Resolve problem
      // 5. Settle directions
      // 6. Claim rewards
      // 7. Verify reputation updates
    });

    it("Should handle multiple simultaneous stakers", async () => {
      console.log("Testing concurrent staking...");
    });

    it("Should correctly distribute rewards based on stake proportion", async () => {
      console.log("Testing reward distribution...");
    });
  });
});

// Helper functions
async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function toDecimal(amount: number, decimals: number = 6): anchor.BN {
  return new anchor.BN(amount * Math.pow(10, decimals));
}

function fromDecimal(amount: anchor.BN, decimals: number = 6): number {
  return amount.toNumber() / Math.pow(10, decimals);
}
